test

diff --git a/.github/workflows/version-bump.yaml b/.github/workflows/version-bump.yaml
--- a/.github/workflows/version-bump.yaml
+++ b/.github/workflows/version-bump.yaml
@@ -22,30 +22,31 @@ jobs:
           git config --global user.name "GitHub Actions Bot"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Install dependencies
-        run: npm install
-
-      - name: Check if package.json was modified
-        id: check_package
+      - name: Check for manual changes to package.json or package-lock.json
+        id: check_manual_changes
         run: |
-          # Check if package.json is modified compared to develop
-          if git diff --name-only develop...HEAD | grep -q "package.json"; then
-            echo "package_modified=true" >> $GITHUB_ENV
-            echo "package.json has been modified in this PR."
+          # Check if package.json or package-lock.json has been modified
+          if git diff --name-only develop...HEAD | grep -Eq "package(-lock)?.json"; then
+            echo "package_files_modified=true" >> $GITHUB_ENV
+            echo "Error: package.json or package-lock.json was modified manually. Failing the build."
+            exit 1  # Fail the build
           else
-            echo "package_modified=false" >> $GITHUB_ENV
-            echo "package.json has NOT been modified in this PR."
+            echo "package_files_modified=false" >> $GITHUB_ENV
           fi
 
+      - name: Install dependencies
+        if: env.package_files_modified == 'false'
+        run: npm install
+
       - name: Bump version with custom commit message
-        if: env.package_modified == 'false'
+        if: env.package_files_modified == 'false'
         run: |
           npm version minor -m "chore: bump version to %s for PR"
           new_version=$(jq -r .version package.json)
           echo "New version is $new_version"
-
+      
       - name: Push version bump commit
-        if: env.package_modified == 'false'
+        if: env.package_files_modified == 'false'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
